Update build-xiaomi_3.yml
Signed-off-by: ljq2023 <jqj62285@gmail.com>

diff --git a/.github/workflows/build-xiaomi_3.yml b/.github/workflows/build-xiaomi_3.yml
--- a/.github/workflows/build-xiaomi_3.yml
+++ b/.github/workflows/build-xiaomi_3.yml
@@ -18,7 +18,11 @@ jobs:
           sudo add-apt-repository universe
           sudo apt update
           sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
-            gettext git libncurses-dev libssl-dev python3.11-distutils rsync unzip zlib1g-dev file wget
+            gettext git libncurses-dev libssl-dev python3 python3-all rsync unzip zlib1g-dev file wget
+
+      - name: Fix python distutils fallback
+        run: |
+          python3 -m ensurepip --upgrade || echo "ensurepip failed, ignore if already installed"
 
       - name: Clone LEDE source
         run: |
